/** Mô tả ngắn cho nghề gợi ý (fallback khi không có trong map). */

const MAP: Record<string, string> = {
  "Kiến trúc sư phần mềm": "Thiết kế hệ thống scalable, API và tích hợp dịch vụ.",
  "Data Scientist": "Phân tích dữ liệu, mô hình và ra quyết định dựa trên số liệu.",
  "Kỹ sư hệ thống": "Vận hành hạ tầng, độ tin cậy và hiệu năng tổng thể.",
  "Product strategy": "Định hướng sản phẩm, ưu tiên roadmap và giá trị người dùng.",
  "An ninh thông tin": "Bảo vệ hệ thống, phát hiện lỗ hổng và tuân thủ bảo mật.",
  "Nghiên cứu AI": "Thử nghiệm mô hình, pipeline ML và ứng dụng thực tế.",
  "Backend engineer": "Xây dựng API, cơ sở dữ liệu và logic phía máy chủ.",
  "Kỹ sư công cụ": "Cải thiện DX: CI/CD, build, automation cho đội ngũ.",
  "Technical writer": "Tài liệu kỹ thuật, hướng dẫn và onboarding rõ ràng.",
  "Game systems": "Cân bằng gameplay, economy và luật trong game.",
  "Quản lý sản phẩm": "Kết nối nhu cầu người dùng, kỹ thuật và kinh doanh.",
  "Tech lead": "Dẫn dắt kỹ thuật, chất lượng code và quyết định kiến trúc.",
  Founder: "Xây dựng sản phẩm từ ý tưởng, đa nhiệm và tốc độ cao.",
  "Quản lý dự án": "Lập kế hoạch, theo dõi tiến độ và phối hợp stakeholder.",
  "Sales kỹ thuật": "Demo giải pháp, tư vấn kỹ thuật cho khách hàng B2B.",
  "Fullstack / startup": "Làm end-to-end: UI, API và triển khai nhanh.",
  DevRel: "Cộng đồng developer, nội dung và hỗ trợ tích hợp.",
  "Giải pháp doanh nghiệp": "Tùy biến sản phẩm cho từng khách hàng lớn.",
  "UX researcher": "Phỏng vấn người dùng, insight và cải thiện trải nghiệm.",
  Automation: "Tự động hóa quy trình, script và tích hợp hệ thống.",
  "UX/UI có tâm lý": "Thiết kế giao diện thân thiện, dựa trên hành vi người dùng.",
  "Giáo dục công nghệ": "Soạn khóa học, workshop và lộ trình học tập.",
  "Content / community": "Nội dung, sự kiện và gắn kết cộng đồng.",
  "Counseling tech": "Ứng dụng công nghệ trong hỗ trợ và tư vấn.",
  "Healthcare IT": "Hệ thống y tế, dữ liệu bệnh nhân và tuân thủ.",
  "Frontend sáng tạo": "Giao diện web hiện đại, animation và trải nghiệm.",
  "Game narrative": "Cốt truyện, quest và thế giới trong game.",
  "Thiết kế tương tác": "Luồng người dùng, prototype và micro-interaction.",
  "Marketing kỹ thuật": "Landing, tracking, growth và công cụ marketing.",
  "Open source": "Đóng góp thư viện, công cụ và cộng đồng mã nguồn mở.",
  "Scrum master": "Facilitate sprint, loại bỏ trở ngại cho nhóm.",
  "People manager": "Phát triển nhân sự, 1:1 và văn hóa đội ngũ.",
  "Customer success": "Onboarding khách hàng, retention và mở rộng sử dụng.",
  "Đào tạo nội bộ": "Chương trình upskill và tài liệu nội bộ.",
  EdTech: "Sản phẩm học tập trực tuyến và cá nhân hóa.",
  "Growth / marketing": "Thử nghiệm kênh, funnel và tăng trưởng người dùng.",
  "Product owner": "Backlog, ưu tiên và giá trị giao cho từng sprint.",
  "Creative technologist": "Kết hợp nghệ thuật và code trong dự án sáng tạo.",
  "Startup generalist": "Đa nhiệm: từ sản phẩm đến vận hành giai đoạn đầu.",
  Evangelist: "Truyền bá công nghệ, talk và demo sản phẩm.",
  DevOps: "CI/CD, container, observability và triển khai.",
  "QA engineer": "Kiểm thử tự động, chất lượng phát hành.",
  "Database admin": "Hiệu năng DB, backup và mô hình dữ liệu.",
  "Kế toán / ERP": "Hệ thống quản trị doanh nghiệp và báo cáo.",
  "Compliance tech": "Tuân thủ quy định, audit trail và kiểm soát truy cập.",
  "Hỗ trợ kỹ thuật": "Giải quyết ticket, hướng dẫn người dùng cuối.",
  "QA manual": "Kịch bản test, regression và báo cáo lỗi.",
  "Internal tools": "Công cụ nội bộ tăng năng suất đội ngũ.",
  "Engineering manager": "Quản lý nhóm kỹ sư, hiring và delivery.",
  "IT operations": "Hạ tầng CNTT, helpdesk và tài sản công nghệ.",
  "Implementation consultant": "Trao đổi triển khai giải pháp cho khách hàng.",
  "Release manager": "Phối hợp phát hành, versioning và rollback.",
  "Admin hệ thống": "Máy chủ, quyền truy cập và giám sát.",
  "Customer support lead": "Đội hỗ trợ, SLA và cải thiện self-service.",
  "Training specialist": "Thiết kế và tổ chức đào tạo cho người dùng/khách.",
  "HR tech": "ATS, onboarding và phân tích nhân sự.",
  "Account manager": "Chăm sóc khách hàng, mở rộng hợp đồng.",
  "Team coordinator": "Lịch họp, tiến độ và giao tiếp liên phòng ban.",
  SRE: "Độ tin cậy site, SLO và phản ứng sự cố.",
  "Embedded / IoT": "Phần mềm nhúng, firmware và thiết bị.",
  "Security pentester": "Kiểm tra xâm nhập và báo cáo rủi ro.",
  "Gameplay programmer": "Logic game, vật lý và cảm giác chơi.",
  "Kỹ thuật phần cứng": "Nguyên mẫu PCB, driver và tích hợp.",
  "UI implementation": "Chuyển design thành component chính xác.",
  "Motion / web creative": "Animation, micro-interaction trên web.",
  "Indie dev": "Tự phát hành sản phẩm nhỏ độc lập.",
  "AR/VR content": "Trải nghiệm không gian và tương tác 3D.",
  "Sound tech": "Âm thanh tương tác và pipeline audio.",
  "Sales engineer": "POC kỹ thuật và đề xuất giải pháp bán hàng.",
  "Field application": "Hỗ trợ triển khai tại hiện trường.",
  "Mobile rapid delivery": "Ship tính năng mobile nhanh theo sprint.",
  "Incident response": "Xử lý sự cố bảo mật và khôi phục.",
  "Solutions architect": "Thiết kế tổng thể giải pháp cho doanh nghiệp.",
  "Demo specialist": "Trình diễn sản phẩm và proof-of-value.",
  "Livestream tech": "Công cụ phát sóng, low-latency và tương tác.",
  "Event tech": "Check-in, streaming và hạ tầng sự kiện.",
  "Mobile apps consumer": "Ứng dụng di động phục vụ người dùng đại chúng.",
  "Creative production": "Sản xuất nội dung đa phương tiện.",
  "Lập trình viên fullstack": "Frontend + backend trong một sản phẩm.",
  "Kỹ sư phần mềm": "Phát triển tính năng, chất lượng và bảo trì.",
  "Chuyên viên phân tích dữ liệu": "Báo cáo, dashboard và insight.",
  "QA / automation": "Test tự động hóa và regression.",
  "AI / ML engineer (mở rộng)": "Huấn luyện/triển khai mô hình trong sản phẩm.",
  "System design / kiến trúc": "Thiết kế hệ thống lớn, khả năng mở rộng.",
  "Technical founder / indie hacker": "Sản phẩm độc lập, MVP và go-to-market.",
};

export function careerShortDescription(title: string): string {
  return MAP[title] ?? "Phù hợp với hồ sơ và sở thích bạn đã thể hiện trong bài test.";
}
