export interface OnboardingQuestion {
  code: string;
  text: string;
  type: "radio" | "checkbox" | "text" | "mbti";
  options?: { value: string; label: string }[];
  required?: boolean;
  group?: "A" | "B" | "C" | "D" | "MBTI";
}

export const onboardingQuestions: OnboardingQuestion[] = [
  {
    code: "A1",
    text: "Bạn học lập trình để làm gì?",
    type: "radio",
    options: [
      { value: "web", label: "Web" },
      { value: "data", label: "Data" },
      { value: "game", label: "Game" },
      { value: "mobile", label: "Mobile" },
      { value: "automation", label: "Automation" },
      { value: "other", label: "Khác" },
    ],
    required: true,
    group: "A",
  },
  {
    code: "A2",
    text: "Bạn muốn đạt được gì sau 3 tháng?",
    type: "radio",
    options: [
      { value: "web_basic", label: "Web cơ bản" },
      { value: "data_analysis", label: "Phân tích dữ liệu" },
      { value: "simple_game", label: "Game đơn giản" },
      { value: "mobile_app", label: "App mobile" },
      { value: "automation", label: "Tự động hóa" },
    ],
    required: true,
    group: "A",
  },
  {
    code: "A3",
    text: "Mỗi ngày bạn có thể dành bao nhiêu giờ học?",
    type: "radio",
    options: [
      { value: "<1", label: "<1h" },
      { value: "1-2", label: "1-2h" },
      { value: "2-4", label: "2-4h" },
      { value: ">4", label: ">4h" },
    ],
    required: true,
    group: "A",
  },
  {
    code: "A4",
    text: "Bạn đã từng học lập trình chưa?",
    type: "radio",
    options: [
      { value: "never", label: "Chưa bao giờ" },
      { value: "self_video", label: "Tự học qua video" },
      { value: "one_course", label: "Đã học 1 khoá" },
      { value: "small_project", label: "Có project nhỏ" },
    ],
    required: true,
    group: "A",
  },
  {
    code: "B1",
    text: "Bạn thích học qua hình thức nào nhất?",
    type: "radio",
    options: [
      { value: "video", label: "Video" },
      { value: "text", label: "Text" },
      { value: "practice", label: "Bài tập ngay" },
      { value: "examples", label: "Ví dụ thực tế" },
    ],
    required: true,
    group: "B",
  },
  {
    code: "B2",
    text: "Khi gặp khó, bạn thường làm gì?",
    type: "radio",
    options: [
      { value: "google", label: "Google" },
      { value: "friend", label: "Hỏi bạn" },
      { value: "ai", label: "Hỏi AI" },
      { value: "review", label: "Xem lại lý thuyết" },
    ],
    required: true,
    group: "B",
  },
  {
    code: "B3",
    text: "Bạn có thích lộ trình cố định không?",
    type: "radio",
    options: [
      { value: "very", label: "Rất thích" },
      { value: "maybe", label: "Có thể" },
      { value: "no", label: "Không" },
      { value: "self", label: "Tự tạo" },
    ],
    required: true,
    group: "B",
  },
  {
    code: "B4",
    text: "Bạn muốn bài tập khó hay dễ?",
    type: "radio",
    options: [
      { value: "easy", label: "Dễ" },
      { value: "medium", label: "Vừa" },
      { value: "challenge", label: "Thử thách" },
      { value: "very_hard", label: "Rất khó" },
    ],
    required: true,
    group: "B",
  },
  {
    code: "B5",
    text: "Bạn có thích học nhóm không?",
    type: "radio",
    options: [
      { value: "very", label: "Rất thích" },
      { value: "sometimes", label: "Thỉnh thoảng" },
      { value: "no", label: "Không" },
      { value: "alone", label: "Một mình" },
    ],
    required: true,
    group: "B",
  },
  {
    code: "B6",
    text: "Bạn muốn nhận thông báo qua?",
    type: "radio",
    options: [
      { value: "email", label: "Email" },
      { value: "telegram", label: "Telegram" },
      { value: "none", label: "Không" },
      { value: "inapp", label: "In-app" },
    ],
    required: true,
    group: "B",
  },
  {
    code: "C1",
    text: "Bạn biết ngôn ngữ nào? (chọn nhiều)",
    type: "checkbox",
    options: [
      { value: "python", label: "Python" },
      { value: "js", label: "JavaScript" },
      { value: "cpp", label: "C++" },
      { value: "java", label: "Java" },
      { value: "htmlcss", label: "HTML/CSS" },
      { value: "none", label: "Chưa biết gì" },
    ],
    required: true,
    group: "C",
  },
  {
    code: "C2",
    text: "Bạn biết Git chưa?",
    type: "radio",
    options: [
      { value: "no", label: "Chưa" },
      { value: "basic", label: "Cơ bản" },
      { value: "proficient", label: "Thành thạo" },
    ],
    required: true,
    group: "C",
  },
  {
    code: "C3",
    text: "Tiếng Anh đọc tài liệu?",
    type: "radio",
    options: [
      { value: "bad", label: "Kém" },
      { value: "dictionary", label: "Dùng từ điển" },
      { value: "basic", label: "Cơ bản" },
      { value: "good", label: "Tốt" },
    ],
    required: true,
    group: "C",
  },
  {
    code: "C4",
    text: "Bạn có kiên trì học đều không?",
    type: "radio",
    options: [
      { value: "very_hard", label: "Rất khó" },
      { value: "sometimes", label: "Thỉnh thoảng" },
      { value: "quite", label: "Khá đều" },
      { value: "very", label: "Rất đều" },
    ],
    required: true,
    group: "C",
  },
  {
    code: "C5",
    text: "Bạn thích debug thế nào?",
    type: "radio",
    options: [
      { value: "ai_do", label: "AI làm hộ" },
      { value: "ai_suggest", label: "AI gợi ý" },
      { value: "self", label: "Tự mò" },
      { value: "ask", label: "Nhờ người" },
    ],
    required: true,
    group: "C",
  },
  {
    code: "D1",
    text: "Bạn thích làm ứng dụng gì nhất?",
    type: "radio",
    options: [
      { value: "game", label: "Game" },
      { value: "website", label: "Website" },
      { value: "mobile", label: "App mobile" },
      { value: "automation", label: "Tự động" },
      { value: "data", label: "Data" },
      { value: "other", label: "Khác" },
    ],
    required: false,
    group: "D",
  },
  {
    code: "D2",
    text: "Ngoài code, bạn đam mê lĩnh vực nào?",
    type: "radio",
    options: [
      { value: "art", label: "Nghệ thuật" },
      { value: "music", label: "Âm nhạc" },
      { value: "sports", label: "Thể thao" },
      { value: "science", label: "KH" },
      { value: "business", label: "Kinh doanh" },
      { value: "cooking", label: "Nấu ăn" },
      { value: "travel", label: "Du lịch" },
    ],
    required: false,
    group: "D",
  },
  {
    code: "D3",
    text: "Bạn muốn giải quyết vấn đề gì?",
    type: "radio",
    options: [
      { value: "environment", label: "Môi trường" },
      { value: "education", label: "Giáo dục" },
      { value: "health", label: "Sức khoẻ" },
      { value: "traffic", label: "Giao thông" },
      { value: "security", label: "An ninh" },
      { value: "other", label: "Khác" },
    ],
    required: false,
    group: "D",
  },
  {
    code: "D4",
    text: "Hứng thú với AI/ML?",
    type: "radio",
    options: [
      { value: "very", label: "Rất thích" },
      { value: "normal", label: "Bình thường" },
      { value: "no", label: "Không" },
    ],
    required: false,
    group: "D",
  },
  {
    code: "D5",
    text: "Muốn học ngoại ngữ nào?",
    type: "radio",
    options: [
      { value: "zh", label: "Trung" },
      { value: "jp", label: "Nhật" },
      { value: "kr", label: "Hàn" },
      { value: "de", label: "Đức" },
      { value: "fr", label: "Pháp" },
      { value: "none", label: "Không" },
    ],
    required: false,
    group: "D",
  },
  {
    code: "MBTI_1",
    text: "Bạn thích làm việc nhóm, trao đổi nhiều (A) hay thích làm việc một mình, yên tĩnh (B)?",
    type: "mbti",
    options: [
      { value: "E", label: "A - Làm việc nhóm" },
      { value: "I", label: "B - Một mình" },
    ],
    required: true,
    group: "MBTI",
  },
  {
    code: "MBTI_2",
    text: "Bạn thích học qua thảo luận, nói ra (A) hay thích đọc và suy ngẫm trước (B)?",
    type: "mbti",
    options: [
      { value: "E", label: "A - Thảo luận" },
      { value: "I", label: "B - Suy ngẫm" },
    ],
    required: true,
    group: "MBTI",
  },
  {
    code: "MBTI_3",
    text: "Bạn thích học theo từng bước cụ thể (A) hay nhìn tổng thể, ý tưởng lớn (B)?",
    type: "mbti",
    options: [
      { value: "S", label: "A - Từng bước" },
      { value: "N", label: "B - Tổng thể" },
    ],
    required: true,
    group: "MBTI",
  },
  {
    code: "MBTI_4",
    text: "Bạn thích ví dụ thực tế, dễ hình dung (A) hay lý thuyết trừu tượng, khái niệm (B)?",
    type: "mbti",
    options: [
      { value: "S", label: "A - Thực tế" },
      { value: "N", label: "B - Trừu tượng" },
    ],
    required: true,
    group: "MBTI",
  },
  {
    code: "MBTI_5",
    text: "Bạn quyết định dựa trên logic, phân tích (A) hay cảm xúc, giá trị (B)?",
    type: "mbti",
    options: [
      { value: "T", label: "A - Logic" },
      { value: "F", label: "B - Cảm xúc" },
    ],
    required: true,
    group: "MBTI",
  },
  {
    code: "MBTI_6",
    text: "Bạn phê bình thẳng thắn, coi trọng sự thật (A) hay thích khích lệ, tránh gây mất lòng (B)?",
    type: "mbti",
    options: [
      { value: "T", label: "A - Thẳng thắn" },
      { value: "F", label: "B - Khích lệ" },
    ],
    required: true,
    group: "MBTI",
  },
  {
    code: "MBTI_7",
    text: "Bạn thích lên kế hoạch rõ ràng, đúng deadline (A) hay linh hoạt, không gò bó (B)?",
    type: "mbti",
    options: [
      { value: "J", label: "A - Kế hoạch" },
      { value: "P", label: "B - Linh hoạt" },
    ],
    required: true,
    group: "MBTI",
  },
  {
    code: "MBTI_8",
    text: "Bạn thích kết thúc công việc trước khi nghỉ (A) hay làm nhiều việc cùng lúc, thoải mái (B)?",
    type: "mbti",
    options: [
      { value: "J", label: "A - Kết thúc trước" },
      { value: "P", label: "B - Làm cùng lúc" },
    ],
    required: true,
    group: "MBTI",
  },
  {
    code: "MBTI_9",
    text: "Bạn thích có lộ trình chi tiết (A) hay chỉ cần mục tiêu chung (B)?",
    type: "mbti",
    options: [
      { value: "J", label: "A - Chi tiết" },
      { value: "P", label: "B - Mục tiêu chung" },
    ],
    required: true,
    group: "MBTI",
  },
  {
    code: "MBTI_10",
    text: "Bạn thường bắt đầu bài tập sớm (A) hay sát deadline (B)?",
    type: "mbti",
    options: [
      { value: "J", label: "A - Sớm" },
      { value: "P", label: "B - Sát deadline" },
    ],
    required: true,
    group: "MBTI",
  },
];
